backend:
  name: test-repo
  #name: git-gateway

media_folder: "public/admin/content"

media_library:
  name: cloudinary
  config:
    cloud_name: sgrvl
    api_key: 474894817422344

collections:
  - name: "content"
    label: "Content"
    files:
      - label: "Albums"
        name: "albums"
        file: "/albums.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: desc, widget: string }
          - { label: Image, name: image, widget: image }
