backend:
  #name: git-gateway
  name: test-repo
  branch: master
media_folder: content/img
media_library:
  name: cloudinary
  config:
    cloud_name: sgrvl
    api_key: 474894817422344
collections:
  - name: "albums"
    label: "Albums"
    label_singular: "Album"
    folder: "content/album"
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Image ", name: "image", widget: "image" }
  - name: "sizes"
    label: "Sizes & Prices"
    label_singular: "Size & Price"
    folder: "content/sizes"
    create: true
    format: "json"
    fields:
      - { label: "Size", name: "size", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
